disp('Adding Simulated Surgery Matlab Folders to Path');
currDir = cd();
addpath(fullfile(currDir,'CodeOptimization'));
addpath(fullfile(currDir,'DevCode'));
addpath(fullfile(currDir,'ErrorDetection'));
addpath(fullfile(currDir,'ImageAlgo'));
addpath(fullfile(currDir,'ImageUtil'));
addpath(fullfile(currDir,'ImPro'));
addpath(fullfile(currDir,'ResultsViewer'));
addpath(fullfile(currDir,'Scripts'));
addpath(fullfile(currDir,'StereoCalibration'));
addpath(fullfile(currDir,'SyntheticData'));
addpath(fullfile(currDir,'SystemEvaluation'));
addpath(fullfile(currDir,'TrackingAlgo'));
addpath(fullfile(currDir,'TrajectoryEstimation'));
addpath(fullfile(currDir,'UserGuidedTracking'));
addpath(fullfile(currDir,'UserGuidedTracking','VirtualDub'));
addpath(fullfile(currDir,'VideoAnalysisTools'));
addpath(fullfile(currDir,'VideoPro'));
addpath(fullfile(currDir,'Vision'));