function [tempNew,neighbNew,maxScore,fitMSE,simSurf] = ...
                 findTempMatch_w(frameIm,pc,nCurr,nSize)
% FINDTEMPMATCH_W Finds best match to template in frame neighborhood
%
% [TEMPNEW,NEIGHBNEW,MAXSCORE,FITMSE,SIMSURF] = ...
%           findTempMatch(FRAMEIM,PC,NCURR,NSIZE)
% Given a structure PC generated by wMatchBuildPcStruct that contains
% template and weighting window information and search neighborhood window
% (upper left hand corner [x,y]->NCURR, NSIZE) finds best match in image
% FRAMEIM using NCC.  Utilizes location of template window in previous
% image [x,y]->TCURR (window upper left hand corner) to find new template
% window upper left hand corner [x,y]->TEMPNEW and search neighborhood
% upper left hand corner [x,y]->NEIGHBNEW.
%
% Input Variables
% FRAMEIM Image to search for template match in
% PC Structure with data related to template and weighting window
% NCURR 2 element array [x,y].  Define location of upper left hand corner
% of search window.
% NSIZE The width and height of search window.
%
% Output Variables
% TEMPNEW Upper left hand corner of best template match in FRAMEIM of same
% size as TEMPLATE
% NEIGHBNEW Upper left hand corner of next search window.  A window with
% width and height NSIZE with upper left corner NEIGHBNEW is centered on the
% window defined by TEMPNEW.
% MAXSCORE The similairty score associated with the match.
% FITMSE The MSE of the subpixel maxima fit
% SIMSURF Similarity Surface used to find best match location.

%% Input Arguments
tSize = size(pc.t,1); % Assumes Square Template
halfWidth = (tSize-1)/2; % Half the Template Window Width

% Define Pixels in search neighborhood.  Prevent Searching outside the
% image
nx = max([1,nCurr(1)]):min(nCurr(1)+(nSize-1),size(frameIm,2));
ny = max([1,nCurr(2)]):min(nCurr(2)+(nSize-1),size(frameIm,1));

nccScore = binWeightedNCC(double(frameIm(ny,nx,:)),pc);

% Neighborhood Mask
% Compute nccMask to exclude windows that don't fit in neighborhood
nMask = false(numel(ny),numel(nx));
nMask((1 + halfWidth):(end - halfWidth),...
      (1 + halfWidth):(end - halfWidth)) = 1; 

% Mask out values outside of nccMask
nccScore = nMask .* abs(nccScore);

% Find maximum of nccScore within nccMask
nccInner = nccScore((1 + halfWidth):(end - halfWidth),...
                    (1 + halfWidth):(end - halfWidth));
[maxScore,maxDex] = max(nccInner(:));
[maxRow,maxCol] = ind2sub(size(nccInner),maxDex);

% Transform coordinates from inner window to nccScore
maxRow = maxRow + halfWidth;
maxCol = maxCol + halfWidth;
if(nargout == 5); simSurf = nccScore; end;

%% Subpixel Estimation
% Only do subpixel estimation if a decent match has been found
if(maxScore > 0.1)
    [subAdjust,fitMSE] = peakfit2d_mod(nccScore( (-1:1)+maxRow, (-1:1)+maxCol));

    % Check for Subfitting Error
    if(all(abs(subAdjust) < 1))
        maxCol = subAdjust(1) + maxCol;
        maxRow = subAdjust(2) + maxRow;
    end
else
    % fitMSE value needed for function output arguments
    fitMSE = nan;
end

%% Outputs
% Upper Left Corner Best Match Window in Absolute Coordinates
maxCoords = [nx(1),ny(1)] + ...
            (([maxCol,maxRow] - ((tSize - 1)/2 * ones(1,2))) - ones(1,2));

% Update Template & Neighborhood
tempNew = maxCoords;
neighbNew = tempNew - (round((nSize - tSize)/2)*[1,1]);

